---
properties:
- name: HELM_VERSION
  value: '2.12.3'
  type: text
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${GIT_REPO}
    service2: $env.foo
    service3: $$env.foo
  triggers:
  - type: commit
