version: '2'
template:
  name: "Cloud Functions REST APIs Toolchain"
  description: "Deploy Serverless REST APIs"
  required:
    - build
    - repo
  info:
    git url: >-
      [https://github.com/IBM/ibm-cloud-functions-refarch-serverless-apis](https://github.com/IBM/ibm-cloud-functions-refarch-serverless-apis)
    git branch: >-
      [master](https://github.com/IBM/ibm-cloud-functions-refarch-serverless-apis/tree/master)
toolchain:
  name: 'cloud-functions-apis-toolchain'
services:
  frontend-repo:
    $default: 'githubpublic'
    $options:
      - $ifdef: 'hostedgit'
        service_id: hostedgit
        parameters:
          repo_name: 'frontend-repo-onhostedgit'
          repo_url: 'https://www.git.com/otc/frontend-repo-onhostedgit'
          type: clone
          has_issues: true
          enable_traceability: true
      - $ifdef: 'githubpublic'
        service_id: githubpublic
        parameters:
          repo_name: 'frontend-repo-ongithubpublic'
          repo_url: 'https://www.github.com/otc/frontend-repo-ongithubpublic'
          type: clone
          has_issues: true
          enable_traceability: true
  middleware-repo:
    service_id: hostedgit
    parameters:
      repo_name: 'middleware-repo-onhostedgit'
      repo_url: 'https://www.git.com/otc/middleware-repo-onhostedgit'
      type: clone
      has_issues: true
      enable_traceability: true
  backend-repo:
    $parameter: 'backend_source_provider'
    $default: 'githubpublic'
    $options:
      - $ifdef: 'hostedgit'
        service_id: hostedgit
        parameters:
          repo_name: 'backend-repo-onhostedgit'
          repo_url: 'https://www.git.com/backend-repo'
          type: clone
          has_issues: true
          enable_traceability: true
      - $ifdef: 'githubpublic'
        service_id: githubpublic
        parameters:
          repo_name: 'backend-repo-ongithubpublic'
          repo_url: 'https://github.com/otc/backend-repo-ongithubpublic'
          type: clone
          has_issues: true
      - $ifdef: 'github_integrated'
        service_id: github_integrated
        parameters:
          repo_name: 'backend-repo-ongithub_integrated'
          repo_url: 'https://cloud.ibm.github.com/otc/backend-repo-ongithub_integrated'
          type: clone
          has_issues: true
          enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo1
          USERNAME: '{{form.pipeline.parameters.username}}'
          PASSWORD: '{{form.pipeline.parameters.password}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          SPACE: '{{form.pipeline.parameters.space}}'
          ORG: '{{form.pipeline.parameters.organization}}'
          REGION: '{{form.pipeline.parameters.region}}'
          GROUP: '{{form.pipeline.parameters.group}}'
        execute: true
form:
  pipeline:
    parameters:
      username: 'admin'
    schema:
      $ref: deploy.json
