version: '2'

template:
  name: "DYML - $env Template Path & Query Context"
  description: "DYML - $env Template Path & Query Context"
  required:
    - repo
  info:
    git url: >
      '[' + $env.repository + '](' + $env.repository + ')'
    git branch: >
      '[' + $env.branch + ']('+ $env.repository + '/tree/' + $env.branch + ')'

toolchain:
  name: 'DYML - $env Template Path & Query Context'

services:
  repo:
    service_id: hostedgit
    parameters:

      # $env params...
      env1: $env.services.repo.service_id
      env2: $env.services.build.parameters.test5
      env3: $env.form.pipeline.parameters.user
      env4: $env.toolchain.name
      env5: $env.template.name
      env6: $env.version
      env7: $env.foo
      env8: $env.foo.bar
      env9: $env.services.repo
      env10: $env.services.repo.parameters
      #env11: $env.services
      #env12: $env.form
      env13: >
        $env.services.repo.parameters.env1 === $env.services.build.parameters.test5

      # mustache params...
      #must1: "{{services.repo.service_id}}"
      #must2: "{{services.build.parameters.test5}}"
      #must3: "{{form.pipeline.parameters.user}}"
      #must4: "{{toolchain.name}}"
      #must5: "{{template.name}}"
      #must6: "{{version}}"
      #must7: "{{foo}}"
      #must8: "{{foo.bar}}"

  build:
    service_id: pipeline
    parameters:
      test5: "hello world"

form:
  pipeline:
    parameters:
      user: admin
    schema: {}
