version: '2'

template:
  name: "DYML: Simple"
  description: "DYML: Simple"
  required:
    - repo

  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"

toolchain:
  name: 'DYML: Simple'

services:
  repo:
    service_id: hostedgit
    parameters:
      test4: >
        $env.services.build.service_id ?
          $env.services.build.service_id :
            "don't have it!"
      test5: >
        $env.____$____.____$$yml$$____.services.build.service_id ?
          $env.____$____.____$$yml$$____.services.build.service_id :
            "don't have it!"

  build:
    service_id: pipeline
    parameters:
      test5: "hello world"

form:
  pipeline:
    parameters: {}
    schema: {}
