version: '2'
template:
  name: "Dynamic Source Providers Template"
  description: "Dynamic Source Providers Template"
  required:
    - build
    - frontend-repo
  info:
    git url: >-
      [https://github.com/tonymcguckin/dynamic-source-providers-template](https://github.com/tonymcguckin/dynamic-source-providers-template)
    git branch: >-
      [master](https://github.com/tonymcguckin/dynamic-source-providers-template/tree/master)
toolchain:
  name: 'dynamic-source-providers-template-toolchain'
services:
  frontend-repo:
    $parameter: 'source_provider'
    $default: 'githubpublic'
    $options:
      - $ifdef: 'hostedgit'
        service_id: 'hostedgit'
        parameters:
          app_repo1: $parameter.app_repo
          app_repo2: '$parameter.app_repo'
          app_repo3: "$parameter.app_repo"
          
          app_repo4: {{app_repo}}
          app_repo5: '{{app_repo}}'
          app_repo6: "{{app_repo}}"
          
          test: $parameter.test
          
          test1: $parameter.test1 || {{timestamp}}
          test2: $parameter.test2 || '{{timestamp}}'
          test3: $parameter.test3 || "{{timestamp}}"
          
          test4: $parameter.test4||{{timestamp}}
          test5: $parameter.test5||'{{timestamp}}'
          test6: $parameter.test6||"{{timestamp}}"
          
          test7: '$parameter.test7 || {{timestamp}}'
          test8: "$parameter.test8||{{timestamp}}"
          
          test9: {{test}}
          test10: '{{test}}'
          test11: "{{test}}"
          
          test12: $parameter.test12 || a7b9ddef66a
          test13: $parameter.test13 || 'a7b9ddef66a'
          test14: $parameter.test14 || "a7b9ddef66a"
          
          test15: $parameter.test15||c6a8f7ac87c
          test16: $parameter.test16||'c6a8f7ac87c'
          test17: $parameter.test17||"c6a8f7ac87c"
          
          test18: $parameter.test18 || "{{form.pipeline.parameters.username}} says its currently {{timestamp}} ms"
          test19: $parameter.test19 || "{{organisation}} org - {{region}} region - {{space}} space"
          
          enable_traceability: true
          has_issues: true
          repo_name: 'frontend-repo-onhostedgit'
          repo_url: 'https://www.git.com/open-toolchain/java-spring-microservice'
          type: clone
          
      - $ifdef: 'githubpublic'
        service_id: 'githubpublic'
        parameters:
          repo_name: 'frontend-repo-ongithubpublic'
          app_repo: {{app_repo}}
          repo_url: $parameter.respository
          type: $parameter.type || "link"
          has_issues: $parameter.issues || true
          enable_traceability: true
  build:
    $parameter: 'pipeline'
    $default: 'p1'
    $options:
      - $ifdef: 'p1'
        service_id: pipeline
        parameters:
          services:
            - frontend-repo
          name: 'Pipeline 1'
          ui-pipeline: true
          configuration:
            content:
              $text: pipeline.yml
            env:
              REPO: frontend-repo
              USERNAME: '{{form.pipeline.parameters.username}}'
              PASSWORD: '{{form.pipeline.parameters.password}}'
              API_KEY: '{{form.pipeline.parameters.api-key}}'
              SPACE: '{{form.pipeline.parameters.space}}'
              ORG: '{{form.pipeline.parameters.organization}}'
              REGION: '{{form.pipeline.parameters.region}}'
              GROUP: '{{form.pipeline.parameters.group}}'
            execute: true
      - $ifdef: 'p2'
        service_id: pipeline
        parameters:
          services:
            - frontend-repo
          name: 'Pipeline 2'
          ui-pipeline: true
          configuration:
            content:
              $text: pipeline.yml
            env:
              REPO: frontend-repo
              USERNAME: '{{form.pipeline.parameters.username}}'
              PASSWORD: '{{form.pipeline.parameters.password}}'
              API_KEY: '{{form.pipeline.parameters.api-key}}'
              SPACE: '{{form.pipeline.parameters.space}}'
              ORG: '{{form.pipeline.parameters.organization}}'
              REGION: '{{form.pipeline.parameters.region}}'
              GROUP: '{{form.pipeline.parameters.group}}'
            execute: true
form:
  pipeline:
    parameters:
      username: 'admin'
    schema:
      $ref: deploy.json
