version: '2'

template:
  name: "DYML: Simple"
  description: "DYML: Simple"
  required:
    - repo

  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"

toolchain:
  name: 'DYML: Simple'

services:
  repo:
    service_id: hostedgit
    parameters:
      test1: $env.services.repo.service_id
      test2: $env.services.build.parameters.test5
      test3: $env.form.pipeline.parameters.user
      test4: $env.toolchain.name
      test5: $env.template.name
      test6: $env.version

      test7: "{{version}}"

  build:
    service_id: pipeline
    parameters:
      test5: "hello world"

form:
  pipeline:
    parameters:
      user: admin
    schema: {}
