version: '2'
template:
  name: "Dynamic Source Providers Template"
  description: "Dynamic Source Providers Template"
  required:
    - build
    - frontend-repo
  info:
    git url: >-
      [https://github.com/tonymcguckin/dynamic-source-providers-template](https://github.com/tonymcguckin/dynamic-source-providers-template)
    git branch: >-
      [master](https://github.com/tonymcguckin/dynamic-source-providers-template/tree/master)
toolchain:
  name: 'dynamic-source-providers-template-toolchain'
services:
  frontend-repo:
    $parameter: 'source_provider'
    $default: 'githubpublic'
    $options:
      - $ifdef: 'hostedgit'
        service_id: 'hostedgit'
        parameters:
          app_repo: $parameter.app_repo | {{app.params.repo}}
          app_repo2: $parameter.app_repo2 | '{{app.params.repo2}}'
          app_repo3: $parameter.app_repo3 | "{{app.params.repo3}}"
          app_repo4: $parameter.app_repo4|"{{app_repo}}"
          app_repo5: '{{app_repo}}'
          app_repo6: '{{repository}}'
          auth1: $parameter.auth1 | a7b9ddef66a
          auth2: $parameter.auth2 | 'a7b9ddef66a'
          auth3: $parameter.auth3 | "jkeki7837"
          auth4: $parameter.auth4|"53hdyy777"
          bar: '$parameter.bar | somebarstring'
          enable_traceability: true
          foo: $parameter.foo | somefoostring
          has_issues: true
          other: "$parameter.other|someotherstring"
          repo_name: 'frontend-repo-onhostedgit'
          repo_url: 'https://www.git.com/open-toolchain/java-spring-microservice'
          source_provider: #parameter.source_provider
          source_provider2: '#parameter.source_provider'
          source_provider3: "#parameter.source_provider"
          type: clone
      - $ifdef: 'githubpublic'
        service_id: 'githubpublic'
        parameters:
          repo_name: 'frontend-repo-ongithubpublic'
          repo_url: $parameter.app_repo
          repo_url2: #parameter.app_repo
          type: clone
          has_issues: true
          enable_traceability: true
  build:
    $parameter: 'pipeline_type'
    $default: 'my_pipeline'
    $options:
      - $ifdef: 'my_pipeline'
        service_id: pipeline
        parameters:
          services:
            - frontend-repo
          name: '{{services.frontend-repo.parameters.repo_name}}'
          ui-pipeline: true
          configuration:
            content:
              $text: pipeline.yml
            env:
              REPO: frontend-repo
              USERNAME: '{{form.pipeline.parameters.username}}'
              PASSWORD: '{{form.pipeline.parameters.password}}'
              API_KEY: '{{form.pipeline.parameters.api-key}}'
              SPACE: '{{form.pipeline.parameters.space}}'
              ORG: '{{form.pipeline.parameters.organization}}'
              REGION: '{{form.pipeline.parameters.region}}'
              GROUP: '{{form.pipeline.parameters.group}}'
            execute: true
      - $ifdef: 'other_pipeline'
        service_id: pipeline
        parameters:
          services:
            - frontend-repo
          name: '{{services.frontend-repo.parameters.repo_name}}'
          ui-pipeline: true
          configuration:
            content:
              $text: pipeline.yml
            env:
              REPO: frontend-repo
              USERNAME: '{{form.pipeline.parameters.username}}'
              PASSWORD: '{{form.pipeline.parameters.password}}'
              API_KEY: '{{form.pipeline.parameters.api-key}}'
              SPACE: '{{form.pipeline.parameters.space}}'
              ORG: '{{form.pipeline.parameters.organization}}'
              REGION: '{{form.pipeline.parameters.region}}'
              GROUP: '{{form.pipeline.parameters.group}}'
            execute: true
form:
  pipeline:
    parameters:
      username: 'admin'
    schema:
      $ref: deploy.json
