version: '2'

template:
  name: "DYML: pipeline.yml Handling"
  description: "DYML: pipeline.yml Handling"
  required:
    - build
    - repo
  info:
    git url: '"[" + $env.repository + "](" + $env.repository + ")"'
    git branch: '"[" + $env.branch + "](" + $env.repository + "/tree/" + $env.branch + ")"'

toolchain:
  name: 'DYML: pipeline.yml Handling'

services:
  repo:
    service_id: hostedgit
    parameters:
      test: "$env.foo " >-
        "=== 'bar123' ? 'hello world' : 'blah'"

  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: 'Pipeline 1'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          USERNAME: '{{form.pipeline.parameters.username}}'
          PASSWORD: '{{form.pipeline.parameters.password}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          SPACE: '{{form.pipeline.parameters.space}}'
          ORG: '{{form.pipeline.parameters.organization}}'
          REGION: '{{form.pipeline.parameters.region}}'
        execute: true

form:
  pipeline:
    parameters:
      username: 'admin'
      group: 'system'
    schema:
      $ref: deploy.json
